### ISSUE TITLE
Greater than 0

### ISSUE THREAD

**Issue by mikejnpc** [initiate6/bitDump#1]
i assume this doesnt work .. 

      "ckey": "Edit because address has greater than 0 btc balance", 
      "pubkey": "Edit because address has greater than 0 btc balance"

**Comment by initiate6** [comment]
Assume what doesn't work?

**Comment by mikejnpc** [comment]
Your utility.. seems half finished and floods the call for query so it
crashes mid way ...so i assume it doesn't work.

**Comment by initiate6** [comment]
So you decided to open an issue on a project that is nine years old and hasn't been touched since.

Also, WTF would you want to use this tool. It does work but slow as shit. Use hashcat or the million other things out there that can crack bitcoin wallets. lol

Side note, though. You suck at opening issues. Have you never submitted an issue on an open-source project before? Because you did absolutely everything wrong. 

But don't worry, we can turn this into a learning exercise. 

Please read this before posting any more issues to any project: https://stackoverflow.com/help/how-to-ask

Another post that might help you out: https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f

Best of luck in your adventures.
